### ISSUE TITLE
Style: Adicionar eslint e prettier

### ISSUE THREAD

**Issue by FLuiz22** [FLuiz22/ufroad-api#19]
# OVERVIEW

- `eslint` e `prettier` são ferramentas comumente utilizadas em projetos JavaScript para garantir que o estilo de código seja uniforme pelo projeto inteiro. Então é interessante sua adição ao projeto para manter a qualidade do código;

# TASKS

- [x] Adicionar e configurar o eslint;
- [x] Adicionar e configurar o prettier;

**Comment by danieleolivs** [comment]
https://github.com/FLuiz22/ufroad-api/pull/32
